### ISSUE TITLE
Metal renderer not working?

### ISSUE THREAD

**Issue by singalen** [amethyst/bracket-lib#241]
I read the latest commits and saw the great news about Metal support. Yay! Thank you!
Though, when I try Metal, I get this:

```
$ RUST_BACKTRACE=1 cargo run --example dwarfmap --no-default-features --features "webgpu"


warning: unused import: `input::clear_input_state`
  --> bracket-terminal/src/lib.rs:13:16
   |
13 | pub(crate) use input::clear_input_state;
   |                ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `bracket-terminal` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `/Users/vic/src/stepsons/stepsonsrl/depends/bracket-lib/target/debug/examples/dwarfmap`
thread 'main' panicked at 'Error in Surface::configure: requested usage is not supported', /Users/vic/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:204:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:460:5
   2: wgpu::backend::direct::Context::handle_error_fatal
             at /Users/vic/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:204:9
   3: <wgpu::backend::direct::Context as wgpu::Context>::surface_configure
             at /Users/vic/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:910:13
   4: wgpu::Surface::configure
             at /Users/vic/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/lib.rs:3184:9
   5: bracket_terminal::hal::webgpu::init::init_adapter::{{closure}}
             at ./src/hal/webgpu/init.rs:149:5
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
   7: pollster::block_on
             at /Users/vic/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.4/src/lib.rs:132:15
   8: bracket_terminal::hal::webgpu::init::init_raw
             at ./src/hal/webgpu/init.rs:28:9
   9: bracket_terminal::initializer::BTermBuilder::build
             at ./src/initializer.rs:490:27
  10: dwarfmap::main
             at ./examples/dwarfmap.rs:325:19
  11: core::ops::function::FnOnce::call_once
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by thebracket** [comment]
I broke it when I added screenshot support. The `scaler` branch works (at least it works on my macbook air) with this one-liner: https://github.com/amethyst/bracket-lib/commit/92fbf2afbbfd7c807ed649fed901f4c308168ff0

I intended to put that fix into the main branch, apparently I put it in scaler by mistake. I'll get that taken care of this morning (the scaling stuff is nearly ready to merge, so I may just merge it)
